application: coe2043-team-13
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  mime_type: text/css

- url: /image
  static_dir: image
  mime_type: image/jpeg

- url: /.*
  script: guestbook.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
